# Generated by Django 6.0.5 on 2026-05-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='available_person',
            field=models.JSONField(blank=True, default=list, help_text='Ex: ["Maman 🌸", "Mon Époux 🌙", "Mariage ✨", "Camarade 💖", "Pour moi"]'),
        ),
    ]
