# Generated by Django 6.0.5 on 2026-05-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_available_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_person',
        ),
        migrations.AddField(
            model_name='product',
            name='target_options',
            field=models.JSONField(blank=True, default=list, help_text="Ex: ['Maman 🌸', 'Mon Époux 🌙', 'Un Enfant ✨', 'Pour moi']"),
        ),
    ]
