# Generated by Django 6.0.5 on 2026-05-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='included_items',
            field=models.TextField(blank=True, help_text="Éléments inclus dans ce produit (ex: 'Tapis de prière, Chapelet, Sac de transport')", null=True),
        ),
    ]
