# Generated by Django 6.0.5 on 2026-05-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_personal_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='target_options',
        ),
        migrations.AlterField(
            model_name='product',
            name='max_message_chars',
            field=models.PositiveSmallIntegerField(default=200, help_text='Nombre max de caractères pour le message personnalisé'),
        ),
    ]
