# Generated by Django 6.0.5 on 2026-05-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_personal_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
    ]
