# Generated by Django 6.0.5 on 2026-05-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_available_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embroidery_required',
            field=models.BooleanField(default=True, help_text="si coché, le prénom est obligatoire avant d'ajouter au panier."),
        ),
    ]
