# Generated by Django 6.0.5 on 2026-05-24 02:59

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='selected_size',
        ),
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(db_index=True, default=apps.orders.models.generate_order_reference, max_length=20, unique=True),
        ),
    ]
