services:
  - type: web
    name: chicshop
    runtime: python
    repo: https://github.com/alpha-omega99/storeEcom
    plan: free
    region: frankfurt
    
    # Build : uniquement l'installation + collectstatic (pas besoin de DB)
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --settings=config.settings.production
    
    # Start : migrate (DB disponible) + lancement du serveur
    startCommand: |
      python manage.py migrate --noinput --settings=config.settings.production
      gunicorn config.wsgi:application

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ecom_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: chicshop-redis
          type: redis
          property: connectionString
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "chicshop.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://chicshop.onrender.com,http://localhost:3000"
      - key: WHATSAPP_API_TOKEN
        sync: false
      - key: WHATSAPP_ADMIN_NUMBER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

  - type: redis
    name: chicshop-redis
    plan: free
    region: frankfurt
    maxmemoryPolicy: noeviction
    ipAllowList:
      - source: 0.0.0.0/0
        description: Autoriser l'accès pour l'application Django

databases:
  - name: ecom_db
    plan: free
    region: frankfurt